Update to Ruby 2.6.10
Ruby 2.6.5 fails to build on newer versions of macOS with this error:

    closure.c:264:14: error: call to undeclared function 'ffi_prep_closure'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        result = ffi_prep_closure(pcl, cif, callback, (void *)self);
                 ^

We should probably update to an even newer version, but this is the
minimum necessary change to fix the issue.